# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.5"
manifest_format = "2.0"
project_hash = "f5fcc40ed08261b01cb6944138076711d67feec1"

[[deps.CANInterface]]
deps = ["Printf"]
path = "/home/aditya/Desktop/SRT/CANInterface.jl"
uuid = "44756509-f907-4102-b943-bbf9a270a596"
version = "0.1.0"

[[deps.CANUtils]]
deps = ["FixedSizeArrays", "Printf"]
path = "/home/aditya/Desktop/SRT/CANUtils.jl"
uuid = "cda4bd93-d5c6-49f2-9dbf-c90406d773d0"
version = "0.1.0"

[[deps.Collects]]
git-tree-sha1 = "d0b504dbd9ea6a0142845a6f9b4c58b3627c718f"
uuid = "08986516-18db-4a8b-8eaa-f5ef1828d8f1"
version = "1.1.0"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"
version = "1.11.0"

[[deps.FixedSizeArrays]]
deps = ["Collects"]
git-tree-sha1 = "76bb6e6427ba47b22c97b7f2cddc1ae002e6a9ad"
uuid = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
version = "1.3.0"

    [deps.FixedSizeArrays.extensions]
    FixedSizeArraysAdaptExt = "Adapt"
    FixedSizeArraysRandomExt = "Random"

    [deps.FixedSizeArrays.weakdeps]
    Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
    Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.J1939Parser]]
deps = ["CANUtils", "Printf"]
path = "/home/aditya/Desktop/SRT/J1939Parser.jl"
uuid = "a65d7beb-48e4-42fa-bd3a-ef6c57044cbc"
version = "0.1.0"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"
version = "1.11.0"

[[deps.SystemSimulator]]
deps = ["CANInterface", "CANUtils", "Dates", "J1939Parser"]
path = "."
uuid = "c7bcbf84-9101-467e-8fba-73742d6023ba"
version = "0.1.0"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
version = "1.11.0"
